# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

org.gradle.parallel=false

# Mod Properties
# don't forget to change changelog.md after bumping version
mod_version=6.0.9
maven_group=qouteall
archives_base_name=immersive-portals

modmenu_version=11.0.1
cloth_config_version=15.0.130
sodium_path=maven.modrinth:sodium:mc1.21.11-0.8.1-fabric
iris_path=maven.modrinth:iris:1.10.3+1.21.11-fabric
gravity_changer_version=cd4e3377
dimlib_version=v1.1.0-mc1.21.1
enable_sodium=true
enable_iris=true
enable_pehkui=false
enable_gravity_changer=false
enable_test_mod=false
enable_geckolib=false

# don't forget to update this if branch changes
git_branch=1.21

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.3
loader_version=0.18.3

# Fabric API
fabric_version=0.140.0+1.21.11
