name: Issue Report
description: File an issue report
body:
  - type: dropdown
    id: is_compat
    attributes:
      label: Is it a mod compatibility issue?
      options:
        - "Select One"
        - "Yes"
        - "No"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "
      If you don't know whether it is a mod compatibility issue, 
      backup your world and test it with only Fabric API and Immersive Portals mod.\n\n
      If it's a compatibility issue, please find exactly which mod is incompatible.
      Simply providing a mod list with 100 mods won't be helpful as the maintainer will not know which mod is incompatible.\n\n
      If you don't know which specific mod is incompatible, binary search is a way of finding the incompatible mod without removing the mods one-by-one. The procedure is simple:\n
        1. Backup the world (because removing mod cause its content to be removed).\n
        2. Remove half of the existing mods, and put them aside.\n
        3. Run the game.\n
        4. Does the issue still exist?\n
        If YES: Repeat from step 2 with the current mods.\n
        If NO: Swap out the current mods with the ones set aside, and repeat from step 1.\n
        5. Repeat this process until the problematic mod(s) have been found.\n"
  - type: textarea
    id: link-to-incompat-mods
    attributes:
      label: "If it's a mod compatibility issue, please provide the link(s) to the incompatible mod(s)"
      description: "The link to the incompatible mods (can be Modrinth link, CurseForge link, GitHub link, etc.)"
    validations:
      required: false
  - type: dropdown
    id: mc_version
    attributes:
      label: Minecraft version
      options:
        - "Select One"
        - "1.20.4"
        - "1.20.2"
        - "1.20.1"
        - "1.20"
        - "1.19.4"
        - "1.19.3"
        - "1.19.2"
        - "1.19"
        - "1.18.x"
        - "1.17.x"
        - "Other (specify below)"
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Note: Only versions for **MC 1.20.4 and MC 1.20.2** is being maintained for now. It's recommended to use MC 1.20.2 or MC 1.20.1 now. Fixing issues on older MC versions is in low priority (except security issues)."
  - type: textarea
    id: what-happened
    attributes:
      label: Describe the issue
      description: Describe the issue. Tell how to reproduce the issue. If it crashes, drag the log and crash report to here. It's recommended to also provide the log here. The log may provide important information that does not exist in crash report. The log is `latest.log` in `logs` folder in the game directory.
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### The maintainer may ask questions for clarifying this issue. Simply submitting a vague issue without replying will get ignored."
  - type: markdown
    attributes:
      value: "### Be polite to the developer. Respect the developer's hard work."
